# Main Helm values for Tetragon with Isovalent integrated Grafana stack
serviceAccount:
  create: true
  name: tetragon

operator:
  enabled: true

integratedGrafana:
  enabled: true
  prometheus:
    # If your chart supports persistence flags, keep it off on CRC (uncomment below)
    # persistence:
    #   enabled: false
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 1Gi

grafana:
  # Override at install time if you want: --set grafana.adminPassword=...
  adminPassword: "tetragon"
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
  # wipe any pod annotations that could include old alpha seccomp keys
  podAnnotations: {}

kube-state-metrics:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 64Mi
  podAnnotations: {}