apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: min-openat-arm64
spec:
  podSelector:
    matchNamespaces: [tetragon-demo]
  kprobes:
    - call: "__arm64_sys_openat"
      syscall: false