#yaml-language-server: $schema=/Users/cpedrode/tetragon_darthvader/demo/policies/tracingpolicy-crd.json
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: starwars-block-alliance-ssh
spec:
  kprobes:
    - call: __arm64_sys_connect     # arm64 syscall you already see firing
      syscall: true
      return: false                 # enforce at ENTRY; no LSM needed
      args:
        - index: 0
          type: sock
          label: sk
      selectors:
        - namespaceSelector:
            matchNames: ["tetragon-demo"]
          podSelector:
            matchLabels:
              org: alliance        # xwing has org=alliance
          matchArgs:
            - index: 0
              operator: DPort
              values: ["22"]
          matchActions:
            - action: Sigkill

    # portable alias (harmless if not present on your kernel)
    - call: sys_connect
      syscall: true
      return: false
      args:
        - index: 0
          type: sock
          label: sk
      selectors:
        - namespaceSelector:
            matchNames: ["tetragon-demo"]
          podSelector:
            matchLabels:
              org: alliance
          matchArgs:
            - index: 0
              operator: DPort
              values: ["22"]
          matchActions:
            - action: Sigkill