apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: starwars-block-xwing-ssh-corrected
spec:
  kprobes:
    # A) Syscall path (arm64): connect(fd, sockaddr*, ...)
    - call: __arm64_sys_connect
      syscall: true
      return: false
      args:
        - index: 1          # sockaddr* (destination) is arg1
          type: sockaddr
          label: sa
      selectors:
        - namespaceSelector: { matchNames: ["tetragon-demo"] }
          podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: ["xwing"]
          matchArgs:
            - index: 1
              operator: SPort        # <-- NOT DPort when type is sockaddr
              values: ["22"]
            # (optional) also pin family if you want
            # - index: 1
            #   operator: Family
            #   values: ["AF_INET","AF_INET6"]
          matchActions: [{ action: Sigkill }]

    # (Optional portability alias; harmless if missing)
    - call: sys_connect
      syscall: true
      return: false
      args:
        - index: 1
          type: sockaddr
          label: sa
      selectors:
        - namespaceSelector: { matchNames: ["tetragon-demo"] }
          podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: ["xwing"]
          matchArgs:
            - index: 1
              operator: SPort
              values: ["22"]
          matchActions: [{ action: Sigkill }]

    # B) TCP function path (uses sock@index 0; DPort is valid here)
    - call: tcp_v4_connect
      syscall: false
      return: false
      args:
        - index: 0
          type: sock
          label: sk
      selectors:
        - namespaceSelector: { matchNames: ["tetragon-demo"] }
          podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: ["xwing"]
          matchArgs:
            - index: 0
              operator: DPort
              values: ["22"]
          matchActions: [{ action: Sigkill }]

    - call: tcp_v6_connect
      syscall: false
      return: false
      args:
        - index: 0
          type: sock
          label: sk
      selectors:
        - namespaceSelector: { matchNames: ["tetragon-demo"] }
          podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: ["xwing"]
          matchArgs:
            - index: 0
              operator: DPort
              values: ["22"]
          matchActions: [{ action: Sigkill }]