apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: starwars-activity-dual-arm64
  namespace: tetragon-system
spec:
  kprobes:
    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    # Process execution (Empire)
    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    - call: "do_execveat_common"
      syscall: false
      return: true
      returnArg:
        index: 0
        type: file
      selectors:
        - podSelector:
            matchLabels:
              org: "empire"
              app.kubernetes.io/part-of: "starwars-demo"
          actions:
            - type: EventLog
              event:
                type: syscall
                severity: info
                message: "ðŸš¨ Empire activity detected"
                fields:
                  - name: syscall
                    value: "{{.syscall}}"
                  - name: return_value
                    value: "{{.return_value}}"
                  - name: file_path
                    value: "{{.file_path}}"
                  - name: pod_name
                    value: "{{.pod_name}}"
                  - name: namespace
                    value: "{{.namespace}}"
            # - type: Sigkill               # <â”€â”€ Uncomment to block immediately
            #   matchActions: []

    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    # Process execution (Alliance)
    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    - call: "do_execveat_common"
      syscall: false
      return: true
      returnArg:
        index: 0
        type: file
      selectors:
        - podSelector:
            matchLabels:
              org: "alliance"
              app.kubernetes.io/part-of: "starwars-demo"
          actions:
            - type: EventLog
              event:
                type: syscall
                severity: info
                message: "ðŸ›¡ Alliance action observed"
                fields:
                  - name: syscall
                    value: "{{.syscall}}"
                  - name: return_value
                    value: "{{.return_value}}"
                  - name: file_path
                    value: "{{.file_path}}"
                  - name: pod_name
                    value: "{{.pod_name}}"
                  - name: namespace
                    value: "{{.namespace}}"

    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    # Network connect (Empire only)
    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    - call: "sys_connect"
      syscall: true
      return: true
      returnArg:
        index: 0
        type: int
      selectors:
        - podSelector:
            matchLabels:
              org: "empire"
              app.kubernetes.io/part-of: "starwars-demo"
          namespaceSelector:
            matchNames:
              - tetragon-demo
          actions:
            - type: EventLog
              event:
                type: syscall
                severity: info
                message: "ðŸš¨ Empire network connect attempt"
                fields:
                  - name: syscall
                    value: "{{.syscall}}"
                  - name: return_value
                    value: "{{.return_value}}"
                  - name: pod_name
                    value: "{{.pod_name}}"
                  - name: namespace
                    value: "{{.namespace}}"
            # - type: Sigkill               # <â”€â”€ Uncomment to block immediately
            #   matchActions: []

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  # DNS lookups (Empire only)
  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  dns:
    - selector:
        podSelector:
          matchLabels:
            org: "empire"
            app.kubernetes.io/part-of: "starwars-demo"
      actions:
        - type: EventLog
          event:
            type: dns
            severity: info
            message: "ðŸŒ Empire DNS request detected"
            fields:
              - name: pod_name
                value: "{{.pod_name}}"
              - name: namespace
                value: "{{.namespace}}"
        # - type: Sigkill                  # <â”€â”€ Uncomment to block immediately
        #   matchActions: []